[package]
name = "pyanndata"
version = "0.1.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["data"]

[dependencies]
anndata-rs = { path = "../anndata-rs" }
numpy = "0.17.1"
ndarray = "0.15"
nalgebra-sparse = "0.7"
hdf5 = "0.8"
polars = { version = "0.23", features = ["ndarray"] }
polars-core = "0.23"
polars-arrow = "0.23"
thiserror = "1.0"
rand = "0.8"
flate2 = "1.0"
paste = "1.0"
parking_lot = "0.12"

[dependencies.pyo3]
version = "0.17.1"
features = ["extension-module", "multiple-pymethods"]

[lib]
crate-type = ["lib"]