[package]
name = "pyanndata"
version = "0.2.0"
edition = "2021"
rust-version = "1.65"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/kaizhang/anndata-rs"
homepage = "https://github.com/kaizhang/anndata-rs"
keywords = ["data"]

[dependencies]
anndata = { path = "../anndata" }
anyhow = "1.0"
numpy = "0.17.2"
ndarray = "0.15"
nalgebra-sparse = "0.8"
hdf5 = "0.8"
polars = { version = "0.25", features = ["ndarray"] }
polars-core = "0.25"
polars-arrow = "0.25"
thiserror = "1.0"
rand = "0.8"
flate2 = "1.0"
paste = "1.0"
parking_lot = "0.12"
rayon = "1.5"

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module", "multiple-pymethods", "anyhow"]

[lib]
crate-type = ["lib"]