[package]
name = "pyanndata"
version = "0.1.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["data"]

[dependencies]
anndata-rs = { path = "../anndata-rs" }
numpy = "0.16.2"
ndarray = "0.15.4"
nalgebra-sparse = "0.6.0"
hdf5 = "0.8.1"
polars = { version = "0.20.0", features = ["ndarray"] }
polars-core = "0.20.0"
thiserror = "1.0.30"
rand = "0.8.5"
flate2 = "1.0"
paste = "1.0.7"
parking_lot = "0.12"

[dependencies.pyo3]
version = "0.16.2"
features = ["extension-module", "multiple-pymethods"]

[lib]
crate-type = ["lib"]