[package]
name = "pyanndata"
version = "0.2.1"
edition = "2021"
rust-version = "1.70"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/kaizhang/anndata-rs"
homepage = "https://github.com/kaizhang/anndata-rs"
keywords = ["data"]

[dependencies]
anndata = { path = "../anndata" }
anndata-hdf5 = { path = "../anndata-hdf5" }
anyhow = "1.0"
downcast-rs = "1.2"
numpy = "0.19.0"
ndarray = "0.15"
nalgebra-sparse = "0.9"
hdf5 = "0.8"
polars = { version = "0.31", features = ["ndarray"] }
polars-core = "0.31"
polars-arrow = "0.31"
thiserror = "1.0"
rand = "0.8"
flate2 = "1.0"
paste = "1.0"
parking_lot = "0.12"
rayon = "1.7"

[dependencies.pyo3]
version = "0.19.2"
features = ["extension-module", "multiple-pymethods", "anyhow"]

[lib]
crate-type = ["lib"]