[package]
name = "pyanndata"
version = "0.4.1"
edition = "2021"
rust-version = "1.70"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/kaizhang/anndata-rs"
homepage = "https://github.com/kaizhang/anndata-rs"
keywords = ["data"]

[dependencies]
anndata = "0.4.1"
anndata-hdf5 = "0.3"
anyhow = "1.0"
downcast-rs = "1.2"
numpy = "0.21.0"
ndarray = "0.16"
nalgebra-sparse = "0.10"
hdf5 = "0.8"
polars = { version = "0.41", features = ["ndarray"] }
polars-core = "0.41"
polars-arrow = "0.41"
pyo3-polars = "0.15"
thiserror = "1.0"
rand = "0.8"
flate2 = "1.0"
paste = "1.0"
parking_lot = "0.12"
rayon = "1.10"

[dependencies.pyo3]
version = "0.21.2"
features = ["extension-module", "multiple-pymethods", "anyhow"]

[lib]
crate-type = ["lib"]
