name: Continuous integration

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Install dependency
      run: |
        sudo pip install --upgrade pip
        pip install --user pytest hypothesis \
          Pygments==2.6.1 sphinx==4.4.0 pandoc nbsphinx \
          sphinx-autodoc-typehints sphinx_rtd_theme \
          markupsafe==2.0.1

    - name: Build and test package
      run: |
        cd ${GITHUB_WORKSPACE}/anndata-hdf5 && cargo test --all --no-fail-fast
        cd ${GITHUB_WORKSPACE}/anndata && cargo test --all --no-fail-fast
        cd ${GITHUB_WORKSPACE}/python && \
          pip install --user .
        pytest ${GITHUB_WORKSPACE}/python/tests

    - name: Build doc
      run: |
        cd ${GITHUB_WORKSPACE}
        sphinx-build ${GITHUB_WORKSPACE}/python/docs _build/html

    - name: Upload doc
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: ./_build/html

  upload_gh-page:
    #if: startsWith(github.ref, 'refs/tags/v')
    name: Publish
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
    - name: Download
      uses: actions/download-artifact@v2

    - name: Upload doc
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation
        publish_branch: gh-pages
        force_orphan: true
