[package]
name = "anndata"
version = "0.2.0"
edition = "2021"
rust-version = "1.65"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/kaizhang/anndata-rs"
homepage = "https://github.com/kaizhang/anndata-rs"

[dependencies]
anyhow = "1.0"
indexmap = { version = "1.8", features = ["rayon"] }
itertools = "0.10"
ndarray = { version = "0.15" }
nalgebra-sparse = "0.8"
num = "0.4"
polars = { version = "0.25", features = ["lazy", "decompress", "ndarray", "dtype-full"] }
parking_lot = "0.12"
replace_with = "0.1"
smallvec = "1.10"
rayon = "1.5"
permutation = "0.4"

[dev-dependencies]
#anndata-n5 = { path = '../anndata-n5' }
anndata-hdf5 = { path = '../anndata-hdf5' }
tempfile = "3.2"
criterion = { version = "0.4", features = ["rayon", "plotters", "cargo_bench_support", "html_reports"] }
proptest = "1"
rand = "0.8.5"
ndarray-rand = "0.14"
nalgebra = { version = "0.31", features = ["rand"] }

[[bench]]
name = "main"
harness = false